[ci] refs #1996 - Try gcc@7 formula with xcode8.3 image
... since gcc@6 fails as follows
```
$ CC=gcc-6 make test-libc

mkdir -p build/usr/tmp build/usr/lib build/usr/include

mkdir -p build/libskycoin bin include

rm -Rf build/libskycoin/libskycoin.a

go build -buildmode=c-archive -o build/libskycoin/libskycoin.a  ./lib/cgo/api.webrpc.client.go ./lib/cgo/cipher.address.go ./lib/cgo/cipher.bitcoin.go ./lib/cgo/cipher.crypto.go ./lib/cgo/cipher.hash.go ./lib/cgo/cli.create_rawtx.go ./lib/cgo/coin.outputs.go ./lib/cgo/libsky_error.go ./lib/cgo/libsky_handle.go ./lib/cgo/libsky_mem.go ./lib/cgo/main.go ./lib/cgo/wallet.wallet.go ./lib/cgo/wallet_option.go

# crypto/x509

In file included from /usr/include/Availability.h:190:0,

                 from /usr/include/sys/time.h:69,

                 from /usr/include/sys/sysctl.h:82,

                 from /Users/travis/.gimme/versions/go1.11.1.darwin.amd64/src/crypto/x509/root_cgo_darwin.go:14:

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFDateFormatter.h:53:34: error: "introduced" undeclared here (not in a function)

     kCFISO8601DateFormatWithYear API_AVAILABLE(macosx(10.12), ios(10.0), watchos(3.0), tvos(10.0)) = (1UL << 0),

                                  ^

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:777:39: error: "deprecated" undeclared here (not in a function)

 const CFStringRef kCFURLLabelColorKey API_DEPRECATED("Use NSURLLabelColorKey", macosx(10.6, 10.12), ios(4.0, 10.0), watchos(2.0, 3.0), tvos(9.0, 10.0));

                                       ^

/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:777:39: error: "message" undeclared here (not in a function)

 const CFStringRef kCFURLLabelColorKey API_DEPRECATE const CFStringRef kCFURLLabelColorKey A 10.12), io const CFStringRef kCFURLLabelColorKey A0, 10.0));

                                       ^

In file included from /System/Library/Frameworks/Security.framework/HeadeIn file included from /System/Library/Frameworks/Security.framework/HeadeIn file included from /System/Library/Frameworks/Security.frarom /Users/travis/.gimme/versions/go1.11.1.darwin.amd64/src/crypto/x509/root_cgo_darwin.go:17:

/System/Library/Frameworks/Security.framework/Headers/Authorization.h:192:7: error: variably modified "bytes" at file scope

  char bytes[kAuthorizationExternalFormLength];

       ^~~~~

make: *** [build/libskycoin/libskycoin.a] Error 2
```

p.s. commented out previous build steps to speed up the build